# Generated by Django 5.0.6 on 2024-05-20 18:10

import django.db.models.deletion
import utils.model_validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID объекта')),
                ('created', models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_earlier_than_current], verbose_name='Время создания объекта')),
                ('modified', models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_earlier_than_current], verbose_name='Время изменения объекта')),
                ('category', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'категория QR кода',
                'verbose_name_plural': 'категории QR кодов',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID объекта')),
                ('created', models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_earlier_than_current], verbose_name='Время создания объекта')),
                ('modified', models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_earlier_than_current], verbose_name='Время изменения объекта')),
                ('code_name', models.CharField(max_length=255, verbose_name='Название QR кода')),
                ('direction', models.URLField(verbose_name='URL адрес, куда ведёт QR код')),
                ('end_time', models.DateTimeField(blank=True, null=True, validators=[utils.model_validators.check_later_than_current], verbose_name='Время окончания работы QR кода')),
                ('path_to_file', models.FilePathField(editable=False, verbose_name='Путь до QR Кода')),
                ('category', models.ForeignKey(blank=True, default='Категория не выбрана', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='QR_generator.category', verbose_name='Категория QR кода')),
            ],
            options={
                'verbose_name': 'QR код',
                'verbose_name_plural': 'QR коды',
                'db_table': 'QR_codes',
            },
        ),
    ]
