# Generated by Django 5.0.6 on 2024-05-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP пользователя, перешедшего по коду'),
        ),
    ]
