# Generated by Django 5.0.6 on 2024-05-26 17:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("QR_generator", "0003_hasaccess"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HasAccess",
        ),
    ]
