# Generated by Django 5.0.6 on 2024-06-16 18:29

import utils.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_generator', '0004_delete_hasaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modified',
            field=models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_later_than_current], verbose_name='Время изменения объекта'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='modified',
            field=models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_later_than_current], verbose_name='Время изменения объекта'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='modified',
            field=models.DateTimeField(default=utils.model_validators.get_current_time, editable=False, validators=[utils.model_validators.check_later_than_current], verbose_name='Время изменения объекта'),
        ),
    ]
